name: StargateCommand
main: net.TheDgtl.StargateCommand.StargateCommand
version: 0.0.1
description: Command addon for the Stargate plugin for Bukkit
author: Drakia
depend: [Stargate]
website: http://www.thedgtl.net
commands:
  sgc:
    description: StargateCommand import/export commands.
    usage: |
      /<command> <import/export/cancel> <gate> [force]
      Type: "/<command> import" for help with import
      Type: "/<command> export" for help with export
      Type: "/<command> cancel" to cancel any pending SGC action
  dial:
    description: Dial a stargate
    usage: |
      /<command> <destination>
      /<command> <source> <destination> [network]
permissions:
  stargate.command.import:
    description: Allow the use of /sgc import
    default: op
  stargate.command.export:
    description: Allow the use of /sgc export
    default: op
  stargate.command.dial:
    description: Allow the use of /dial
    default: true
    children:
      stargate.command.dial.interactive: true
      stargate.command.dial.direct: false